name: Run CI
on:
  push:
    branches:
      - '**'
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: .node-version

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run CI checks
        run: npm run ci
