name: Create Release
on: workflow_dispatch
jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          ref: 'master'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: .node-version

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run CI checks
        run: npm run ci

      - name: Create Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          git-message: 'chore: release'
          git-user-name: 'janro1'
          git-user-email: 'code@jannorothfos.com'
          config-file-path: './changelog.config.cjs'

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --access public

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN  }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
